#!/bin/sh

tail -n 800 /var/tmp/thermometer.log|awk -v offset=$1 -v gain=$2 '{printf("echo -ne \"\xFF\xFF\xFF\xFF\xFF\"|dd bs=1 seek=%i of=/dev/fb0 2> /dev/null\n",(FNR-1)*600+($13-offset)*gain)}'|sh

